### ISSUE TITLE
希望可以转制一个firefox版本

### ISSUE THREAD

**Issue by uselessbug** [xlzy520/bilibili-img-uploader#12]
在`https://www.extensiontest.com/`测试通过，希望作者可以转制一下

**Comment by xlzy520** [comment]
@uselessbug 已支持

**Comment by xlzy520** [comment]
![image](https://user-images.githubusercontent.com/28336270/122202229-69972f80-cecf-11eb-94f5-eb9a35e07780.png)

**Comment by xlzy520** [comment]
我的安装方式是解压zip之后，使用`临时载入附加组件`，然后选择manifest.json即可

**Comment by uselessbug** [comment]
好耶

**Comment by uselessbug** [comment]
![新项目](https://user-images.githubusercontent.com/61285640/122320595-0f40b200-cf55-11eb-9a4f-9499406da230.gif)
确实是可以打开扩展的（老版本也可以）
但是上传图片后不会出现链接，也不会出现在列表内

**Comment by xlzy520** [comment]
@uselessbug 经测试，换成你自己最新的cookie即可上传，但是没有提示登录失败，我暂时不知道什么原因，我这边会提示。

然后的话，如果你用typora编辑器的话，你可以试试另一个项目，就是在typora里面粘贴上传到B站的

**Comment by xlzy520** [comment]
还有一个问题的话就是临时载入附加组件的话，好像一关浏览器，插件就没了？我这边是这样，不知道你那边

**Comment by uselessbug** [comment]
> 
> 
> 还有一个问题的话就是临时载入附加组件的话，好像一关浏览器，插件就没了？我这边是这样，不知道你那边
临时载入就是这样的，所以还是打包成xpi更方便。jpg

**Comment by xlzy520** [comment]
@uselessbug 不太清楚Firefox的打包方式，你看看你能改吗

**Comment by uselessbug** [comment]
> 
> 
> @uselessbug 不太清楚Firefox的打包方式，你看看你能改吗

@xlzy520 直接去`https://addons.mozilla.org/zh-CN/developers/addons`提交扩展就好

**Comment by xlzy520** [comment]
@uselessbug 提交审核了，

**Comment by xlzy520** [comment]
@uselessbug 已上架成功
https://addons.mozilla.org/zh-CN/firefox/addon/%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E5%9B%BE%E5%BA%8A/

**Comment by xlzy520** [comment]
@uselessbug 已重构，并且Firefox也更新了
