### ISSUE TITLE
希望能自动生成短链

### ISSUE THREAD

**Issue by Huxzhi** [xlzy520/bilibili-img-uploader#13]

**Comment by xlzy520** [comment]
过段时间增加

**Comment by Huxzhi** [comment]
谢谢，期待😚，个人感觉 整个功能是不是可以独立出来，做一个绿色免安装的软件

我感觉这个浏览器扩展就是一个启动器，跟网页没有关系（）

我看到一些画师在B站发布图片容易被和谐，需要打码，下面又有一堆人求原图，可以把图片短链放到评论区，就不需要去p站搜原图了

**Comment by xlzy520** [comment]
@Huxzhi 可以暂时先用我的短链生成器进行转换

**Comment by Huxzhi** [comment]
> 

已经在用了，效果很好😊。看到短链的作者也是您，就来提需求了，哈哈

**Comment by xlzy520** [comment]
@Huxzhi 已重构，增加短链功能，优化页面

**Comment by xlzy520** [comment]
@Huxzhi 下载最新版即可

**Comment by Huxzhi** [comment]
收到
