### ISSUE TITLE
FireFox 无法复制链接

### ISSUE THREAD

**Issue by stfujnkk** [xlzy520/bilibili-img-uploader#15]
`FireFox` 插件复制链接按钮失效。点击时，显示复制成功，实际上什么结果都没复制或者有时只会给个文件路径。只能导出`json`数据后，复制里面的链接。
但是在`Microsoft Edge`里测试时没有这种情况

**Comment by xlzy520** [comment]
@stfujnkk 已修复，接口问题

**Comment by xlzy520** [comment]
接口问题解决了，复制问题也解决了，等审核一下就行了
