### ISSUE TITLE
本地开发版不能实时更新历史

### ISSUE THREAD

**Issue by uldaman** [xlzy520/bilibili-img-uploader#18]
使用本地开发版时，上传照片后不能实时更新历史，需要重新点开次扩展才行，似乎时 watch 没有起作用

**Comment by xlzy520** [comment]
我后面试试

**Comment by vmpsdkblog** [comment]
“图片上传” 和 “已上传图片” 按钮切换一次才会显示历史上传图

**Comment by xlzy520** [comment]
近期修复

**Comment by xlzy520** [comment]
但是我本地版没有复现诶 @vmpsdkblog

**Comment by vmpsdkblog** [comment]
> 但是我本地版没有复现诶 @vmpsdkblog
这倒是个小问题，昨天开始启用插件B站会加载网页不完整且B站功能异常。
删除浏览器 "Cookie" 重启 "Chrome" 也一样网页加载异常，只有在关闭 “哔哩哔哩图床” 插件后才会恢复正常。
（上一个本地版本没有出现这种情况）
Chrome浏览器版本 88.0.4324.190 x64（正式版本）

![网页加载不完整](https://i0.hdslb.com/bfs/album/b17fc97eae128c68b91356f86e30f81a9a890741.png@1e_1c.webp)
![打开B站直播间报错](https://i0.hdslb.com/bfs/album/2e62ff9936789723aa1e4b5998b64c4a7f683020.png)

**Comment by vmpsdkblog** [comment]
![控制台](https://i0.hdslb.com/bfs/album/31942e9b06d728e7804aa91275908612523c9f66.png)

**Comment by xlzy520** [comment]
@vmpsdkblog 这个新的问题已经修复了，用最新版就行
