### ISSUE TITLE
批量处理

### ISSUE THREAD

**Issue by like977** [xlzy520/bilibili-img-uploader#19]
既然可以批量导出，请问批量导入的格式是什么？

**Comment by xlzy520** [comment]
@like977 和导出的格式一致

**Comment by like977** [comment]
> @like977 和导出的格式一致

默认的edg浏览器是支持多文件上传的，火狐浏览器貌似不支持多文件操作

**Comment by xlzy520** [comment]
@like977 我试了一下，手动点击上传的话，插件页面都被他关了，无语。先用其他浏览器吧。
