### ISSUE TITLE
Gitbook防盗链问题

### ISSUE THREAD

**Issue by Goojoe** [xlzy520/bilibili-img-uploader#20]
像Gitbook这种不能增加HTML标签
```html
<head>
<meta name="referrer" content="no-referrer"/>
</head>
```
防盗链的好像用不了吧
我用的是官网Gitbook同步到Github

**Comment by xlzy520** [comment]
@Goojoe 如果没有其他办法的话，可以用这个方法
https://github.com/xlzy520/picgo-plugin-bilibili/issues/5

**Comment by Goojoe** [comment]
谢谢,已解决
虽然有自建图床,但是还是感觉太慢了
白嫖万岁!
