### ISSUE TITLE
上传失败！

### ISSUE THREAD

**Issue by nanguoyouxue** [xlzy520/bilibili-img-uploader#22]
API依然可用，但是chrome浏览器插件上传失败。API直接返回错误信息，疑似升级了API，屏蔽了插件。😥

**Comment by xlzy520** [comment]
是的，正在想办法解决。

**Comment by xlzy520** [comment]
@nanguoyouxue 已更新，在线安装的还需要审核，操作方式和以前有点不一样

**Comment by nanguoyouxue** [comment]
> @nanguoyouxue 已更新，在线安装的还需要审核，操作方式和以前有点不一样

🎉好的好的
