### ISSUE TITLE
谷歌在线版上传失败

### ISSUE THREAD

**Issue by vmpsdkblog** [xlzy520/bilibili-img-uploader#23]
按照新的自述文档操作 ，没有转到新的Tab页面。
用QQ截图 “Ctrl+Alt+A" 后鼠标对着 “哔哩哔哩图床” 插件空白处按下 “Ctrl+V” 粘贴键,此时的 “哔哩哔哩图床” 插件界面直接收缩到右上角最小化且无任何提示。尝试使用上传功能也没有生效！
我的操作系统信息
![q1](https://user-images.githubusercontent.com/31560266/181882985-c7dc6c8a-d9cf-4b1b-99f2-e501b9cd5fd4.png)
系统版本：Windows 10 Pro x64 (1909 OS 内部版本 18363.693)
Google Chrome版本： 88.0.4324.190x64（正式版本）

**Comment by visiLi** [comment]
是的 我这边也是失败的

**Comment by ICAN1999** [comment]
估计是B站把接口的信息给改了，赶紧想想办法解决呀

**Comment by xlzy520** [comment]
在线商店审核还没有通过，你们先可以通过本地安装的方式进行操作

**Comment by xlzy520** [comment]
代码已修复，商店在审核，可以暂时通过本地安装

**Comment by xlzy520** [comment]
@vmpsdkblog 可以下载最新的本地版2.0.12
