### ISSUE TITLE
添加本地版到Chrome扩展报错的解决方法

### ISSUE THREAD

**Issue by vmpsdkblog** [xlzy520/bilibili-img-uploader#25]
报错：
![2022_1659407706](https://user-images.githubusercontent.com/31560266/182283557-0bdc79f0-4992-4cc5-824f-9a430b7eb963.png)

第一步：
![2022_1659407924](https://user-images.githubusercontent.com/31560266/182283562-a300e14f-4520-4665-a0d7-f6826391256c.png)

第二步：
![2022_1659408771](https://user-images.githubusercontent.com/31560266/182283563-283fca7e-50f1-46e6-81c1-09ee9a60a2f4.png)

后续在线版本能不能修复一下这个问题。

**Comment by xlzy520** [comment]
好的，今天修复

**Comment by xlzy520** [comment]
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/28336270/182285004-e21a6b24-7aa9-4cb8-a796-55a7974f0409.png">
路径看起来是没有问题的

**Comment by vmpsdkblog** [comment]
> <img alt="image" width="1028" src="https://user-images.githubusercontent.com/28336270/182285004-e21a6b24-7aa9-4cb8-a796-55a7974f0409.png">
> 
> 路径看起来是没有问题的

可能是我Chrome版本较低的原因！

**Comment by xlzy520** [comment]
最新版应该已解决

**Comment by xlzy520** [comment]
使用2.0.12
