### ISSUE TITLE
启用后会导致哔哩哔哩无法正常使用

### ISSUE THREAD

**Issue by Goojoe** [xlzy520/bilibili-img-uploader#27]
Chrome Stable 版本 104.0.5112.81（正式版本） （64 位）
哔哩图床插件版本: 2.0.12
![image](https://user-images.githubusercontent.com/78355492/184882035-54a6ca5d-a874-49db-a3f0-b2e73aa2af20.png)
![image](https://user-images.githubusercontent.com/78355492/184882066-ae6f8a10-00ab-4c43-8395-8c49440cd1f8.png)

**Comment by xlzy520** [comment]
@Goojoe 已修复，下载最新版即可
