### ISSUE TITLE
关于透明图片

### ISSUE THREAD

**Issue by paulzzh** [xlzy520/bilibili-img-uploader#29]
今开始似乎上传透明的PNG会被自动添加白底
例如
![image](https://user-images.githubusercontent.com/28055560/189668292-8eee8120-929c-41c4-883c-ae7da224ddbe.png)
上传后会变成
https://i0.hdslb.com/bfs/album/44bc9c18891b838c424536199cf3e6f82d22d68d.png

**Comment by xlzy520** [comment]
@paulzzh 应该是B站处理的
