### ISSUE TITLE
建议：上传后在已上传图片里保留一列显示原图片名字。

### ISSUE THREAD

**Issue by heaid** [xlzy520/bilibili-img-uploader#30]
近期把图片都更换到b站的图床上了，在此非常感谢作者。速度确实非常快。

主要是一次性上传多个图片之后，就没法找到原图挨个复制了，得点开看图片挨个对比。效率有点低。

如果保留一列显示原图片名字，这样可以直接复制，效率会高很多，也不怕搞乱。

![](https://i0.hdslb.com/bfs/album/e655d4fb94790b7ee4b075ba3eb133daa6a1e511.png)

**Comment by xlzy520** [comment]
感谢反馈

**Comment by xlzy520** [comment]
<img width="614" alt="image" src="https://user-images.githubusercontent.com/28336270/211760242-4c4301b4-8d2a-4fef-a597-cde8c2bda5c4.png">
@heaid 已改

**Comment by xlzy520** [comment]
审核中

**Comment by xlzy520** [comment]
@heaid 已通过
