### ISSUE TITLE
B站相簿的上传API抽风，看B站这两天解不解决，不解决就换成动态的上传API

### ISSUE THREAD

**Issue by xlzy520** [xlzy520/bilibili-img-uploader#31]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/28336270/215521427-5e2baac3-3fa9-4f69-84bd-633bd0b86a17.png">
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/28336270/215521479-2f937077-e4f6-45e3-b866-802aab50635e.png">

**Comment by xlzy520** [comment]
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/28336270/215525777-c6c8b2dc-455c-4b48-85f4-95db6875f6a4.png">
动态API上传成功，只是需要多给一个csrf参数

**Comment by zoer98** [comment]
我说今天怎么一直上传失败，正准备发个iuues，看到通知

**Comment by awslnotbad** [comment]
> <img alt="图像" width="1380" src="https://user-images.githubusercontent.com/28336270/215525777-c6c8b2dc-455c-4b48-85f4-95db6875f6a4.png">
> 
> 动态API上传成功，只是需要多给一个csrf参数

现在还是不能上传

**Comment by xlzy520** [comment]
@zoer98 今天

**Comment by xlzy520** [comment]
代码已更新，Chrome商店审核中 @zoer98 @awslnotbad

**Comment by zoer98** [comment]
> 代码已更新，Chrome商店审核中 @zoer98 @awslnotbad

👍赞，能否出个单页面版本，谷歌插件只能在pc使用，想在手机也上传一些东西

**Comment by xlzy520** [comment]
@zoer98 单页面需要依赖服务器资源，有赞助的话倒是可以开发一个

**Comment by zoer98** [comment]
有国内的赞助入口吗，GitHub提供的方式我似乎打不开？

**Comment by xlzy520** [comment]
@zoer98 微信 lv1017866168

**Comment by wushuiyin004** [comment]
相簿的API  还会恢复吗

**Comment by xlzy520** [comment]
已经换了




该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xlzy520/bilibili-img-uploader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月4日(星期六) 晚上7:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xlzy520/bilibili-img-uploader] B站相簿的上传API抽风，看B站这两天解不解决，不解决就换成动态的上传API (Issue #31)





 
相簿的API  还会恢复吗

**Comment by xlzy520** [comment]
Chrome商店已发布
