### ISSUE TITLE
请教一下插件里的“当前SESSDATA”的问题

### ISSUE THREAD

**Issue by wwdok** [xlzy520/bilibili-img-uploader#39]
作者你好，你做的这个插件很棒。
我想问下，插件里的“当前SESSDATA”是不是不能用户自己修改换成自己的，目前这个SESSDATA是你自己的吗

**Comment by xlzy520** [comment]
@wwdok 不是，这个是自动读取的当前浏览器Bilibili这个网站的cookie

**Comment by wwdok** [comment]
好的，多谢，了解了
