### ISSUE TITLE
【Bug】查看旧版本历史记录功能在最新版Chrome浏览器中无效

### ISSUE THREAD

**Issue by MengNianxiaoyao** [xlzy520/bilibili-img-uploader#46]
![image](https://github.com/xlzy520/bilibili-img-uploader/assets/103258286/bf398bbb-02a9-414b-898d-0e5507e23e99)
如图，显示被屏蔽

**Comment by xlzy520** [comment]
@MengNianxiaoyao 鼠标点击地址栏，再按一次回车，可以打开

**Comment by MengNianxiaoyao** [comment]
> @MengNianxiaoyao 鼠标点击地址栏，再按一次回车，可以打开

行了，但这个版本的历史记录在我清了cookie后就不显示了
