### ISSUE TITLE
About PicGo

### ISSUE THREAD

**Issue by ililitk** [xlzy520/bilibili-img-uploader#6]
能否对接下PicGo?

**Comment by xlzy520** [comment]
@imlinnn 最开始我就是用Picgo的，当时的想法也是写一个picgo的bilibili插件，但是当时他只支持流式的上传，所以当时不适合哔哩哔哩，我才写浏览器版本的。
但是我现在也没时间去做一个picgo的插件了

**Comment by xlzy520** [comment]
@imlinnn 如果后续有时间，我再去尝试一下

**Comment by imlinnn** [comment]
好的

**Comment by xlzy520** [comment]
@ililitk 你好，这个插件已实现。https://github.com/xlzy520/picgo-plugin-bilibili
